### ISSUE TITLE
SecBox::zero_out is unsound

### ISSUE THREAD

**Issue by goffrie** [myfreeweb/secstr#15]
Sample code:
```
use secstr::SecBox;
fn main() {
    let mut mybox: SecBox<fn()> = SecBox::new(Box::new(|| println!("hi")));
    mybox.zero_out();
    mybox.unsecure()();
}
```

The `Copy` bound is not sufficient to make it legal to zero out a value of type `T`. Either the bound should be tighter, or `SecBox` should store a `MaybeUninit<T>` (and `zero_out` should be unsafe).

**Comment by myfreeweb** [comment]
hm, what would be the bound for "plain data, definitely not functions"?

**Comment by goffrie** [comment]
I'm not sure that there is one in std unfortunately... something like https://docs.rs/zerocopy/0.3.0/zerocopy/trait.FromBytes.html is probably what you'd want.

**Comment by goffrie** [comment]
https://github.com/rust-lang/project-safe-transmute is probably relevant.
