### ISSUE TITLE
Safety documentation

### ISSUE THREAD

**Issue by aticu** [myfreeweb/secstr#17]
I've developed [a crate](https://github.com/aticu/pre) for my bachelor's thesis to make working with unsafe code a little bit safer.
It works by annotating unsafe functions with the preconditions that need to be upheld for their safety.
A call to an annotated function will fail to compile, unless it is assured at the call site that the preconditions hold.
Assuring this uses another attribute at the call site.

This has two main advantages:

- It is documented in the code why a piece of `unsafe` code is safe.
- This documentation is partially checked by the compiler. If the conditions that need to be upheld change, it can be noticed right away.

I think that secstr could benefit from such safety annotations.
If you're interested, I'd be happy to prepare a pull request to add them (as a dev-dependency).
While doing so, I'd also be going over all `unsafe` code in secstr to find out whether its usage is safe.

If you're not interested, I'd appreciate it, if you could briefly let me know why, as that would be valuable feedback for my thesis.

**Comment by myfreeweb** [comment]
I saw the crate yesterday on /r/rust, it is pretty cool :)

From quickly looking at this crate again, seems like all the uses of `unsafe` are calls to the standard library, libc, or libsodium — I don't think any of them have `pre` annotations?
But according to #15 maybe some of our API should be `unsafe` — I guess that can be annotated.

So yeah, please do make a PR, that would be good.

**Comment by aticu** [comment]
> I don't think any of them have pre annotations?

Not directly, but those can be added using the [`extern_crate` attribute](https://docs.rs/pre/0.1.0/pre/attr.extern_crate.html).

> But according to #15 maybe some of our API should be `unsafe`  — I guess that can be annotated.

Do you want me to change that in the PR then? And would you want the `pre` annotations to be part of your public API (behind a feature flag)?

**Comment by myfreeweb** [comment]
> Do you want me to change that in the PR then?

Sure, go ahead. I don't currently use this crate tbh, I could give you committer access if you want.

> And would you want the pre annotations to be part of your public API (behind a feature flag)?

Yes! (I didn't even think about feature flags, I thought they would always be mandatory haha)

**Comment by aticu** [comment]
> I could give you committer access if you want

I think I'd prefer to open a PR. That way there's a higher chance that a mistake that I might have made is found.

I think I'll leave off the `assure` attributes on the FFI functions, since I don't know enough about those to really verify that they're safe.

Unfortunately I realized that adding preconditions to the function `SecBox::zero_out` wouldn't directly be possible in the general case, because of a current [limitation in pre](https://github.com/aticu/pre#known-limitations) for the stable compiler that does not allow preconditions for functions in `impl` blocks. I could either make it a freestanding function taking a `&mut SecBox` argument or leave off the preconditions and just write the "Safety" section in the documentation - your choice.

Working on this also made me aware of some things that pre really should support (such as `cfg_attr` attributes), so I'll have to add these first.
