### ISSUE TITLE
Calls to `mlock`/`munlock` may be UB

### ISSUE THREAD

**Issue by aticu** [myfreeweb/secstr#19]
While working on #18, I briefly checked the documentation of `mlock`/`munlock` on my system and read that

> The implementation may require that addr be a multiple of {PAGESIZE}.

This is not necessarily the case the way that these functions are implemented in this crate. It is probably possible to fix this, by aligning the address down and extending the length by the offset, however I did not have time to fix that.

**Comment by myfreeweb** [comment]
hm. On FreeBSD, the manpage says

> the addr argument should be aligned to a multiple of the page size.  If the len argument is not a multiple of the page size, it will be rounded up to be so

but the syscall handler in the kernel actually rounds the `addr` down as well:

```c
	start = trunc_page(addr);
	end = round_page(last);
```

Same in OpenBSD:

```c
	/* align address to a page boundary and adjust size accordingly */
	ALIGN_ADDR(addr, size, pageoff);
```

Linux:

```c
	len = PAGE_ALIGN(len + (offset_in_page(start)));
	start &= PAGE_MASK;
```

So it seems pretty safe to assume that the kernel will round the addr down for us.

**Comment by myfreeweb** [comment]
(also, syscalls with bad arguments are not UB, the kernel would just return EINVAL or something. and here we don't care about errors really, this functionality is best-effort)

**Comment by aticu** [comment]
You're right, I didn't look too far into it. I guess this can be closed then.

**Comment by cemeyer** [comment]
`mlock` / `munlock` operate at page-granularity.  It doesn't really make sense to be locking and unlocking smaller objects.

This is easier to understand with `munlock` -- either the kernel rounds a subpage `munlock` down to zero length, in which case locked pages are leaked forever; or the kernel rounds up to the containing page, in which case, the entire page is unlocked.  This is problematic if the page contained two or more "locked" objects, and we only intended to munlock one of them.

Use of mlock/munlock seems to make more sense with some kind of specialized `Allocator`.
