### ISSUE TITLE
Use `std::ptr::write_volatile`

### ISSUE THREAD

**Issue by alexander255** [myfreeweb/secstr#2]
As of Rust 1.9.0 it is finally possible to reliably zero memory in Rust: https://doc.rust-lang.org/std/ptr/fn.write_volatile.html
That function should definitely be used instead of [`std::ptr::write_bytes`](https://github.com/myfreeweb/secstr/blob/master/src/lib.rs#L19) and makes it possible to drop the `libsodium-sys` requirement.

**Comment by myfreeweb** [comment]
ooh nice! I'll do that.

`libsodium-sys` is optional right now, and if it's used, it's not just for zeroing but for comparison too.
