### ISSUE TITLE
The `PartialEq` implementations of `SecVec<T>` and `SecBox<T>` are UB (and wrong) in some cases

### ISSUE THREAD

**Issue by aticu** [myfreeweb/secstr#20]
They all use the `mem::cmp` function, which is (since #18) `unsafe`, because `T` cannot have any padding bytes. If `T` does happen to have padding bytes, the comparison may succeed or it may fail (depending on the equality of the padding bytes).

See the following code for an example ([Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=21463b7ae53cf669d70ade7bc9335ab6)):

```rust
#[derive(Clone, Copy, PartialEq, Eq)]
struct X(u32, u8);

fn main() {
    let x = [X(0x987ab, 0x3f), X(0x243fe87, 0x10)];
    let y = [X(0x987ab, 0x3f), X(0x243fe87, 0x10)];

    if cmp(&x, &y) {
        println!("bytewise: ==");
    } else {
        println!("bytewise: !=");
    }
    
    if x == y {
        println!("derived:  ==");
    } else {
        println!("derived:  !=")
    }
}
```

On the playground this outputs (using a stable `--release` build):

```text
bytewise: !=
derived:  ==
```

`SecUtf8` is not affected, because it just wraps a `SecVec<u8>` and `u8` does not have any padding bytes.

I'm not sure there really is a good way to fix this.

- One option would be to make all ways of constructing these types `unsafe` and mention in the "Safety" section that `T` must not have padding bytes. That would be a pretty pervasive change though and it would require to remove the `From` implementations, because those cannot be `unsafe`. This is pretty much a non-starter.
- Use some kind of `unsafe trait NoPaddingBytes` and add a bound of `T: NoPaddingBytes`. After a (not very thorough) search I could not find anything like that on crates.io, but it shouldn't be too hard to add something like that and implement it for primitive types (and it should even be possible to make it derivable, if I'm not mistaken).

**Comment by myfreeweb** [comment]
Isn't https://docs.rs/zerocopy/0.3.0/zerocopy/trait.Unaligned.html basically that trait?

**Comment by aticu** [comment]
> Isn't https://docs.rs/zerocopy/0.3.0/zerocopy/trait.Unaligned.html basically that trait?

No, because for example `u32` does not implement `Unaligned` (because it has an alignment of `4`), but a `u32` also clearly has no padding bytes.

**Comment by myfreeweb** [comment]
Argh. I kinda wish I didn't accept the `SecVec`/`SecBox` PR now, haha. I only cared about utf8 strings, and now I don't really care about this crate at all…

I'd be fine with a trait that restricts all of this stuff to just numbers.
