### ISSUE TITLE
Allow to resize SecVec

### ISSUE THREAD

**Issue by timvisee** [myfreeweb/secstr#22]
Currently the [`SecVec`](https://docs.rs/secstr/0.4.0/secstr/struct.SecVec.html) exposes a slice and mutable slice through the 'unsecure' functions. It's size is static. I would like to mutate a `SecVec` where the data length changes however.

At the moment I have to allocate a new `SecVec` to replace the old one to achieve this.

I understand that a `&mut Vec<T>` cannot be exposed, it does allow arbitrary resizing and would be much more convenient, but introduces the problem that you don't have control on where data moves when reallocation occurs. As far as I understand, a resize function could be securely implemented however which would help reach the same goal.

The resize function could look something like this:

```rust
impl SecVec<T> {
    pub fn resize<T: Copy>(&mut self, size: usize, default: T);
}
```

If the new size is smaller, it would truncate. If the new size is larger, it would grow the inner vector, copying the given `default` value where needed for initialization. If a reallocation occurs, the new memory region could be re-secured.

This is more convenient than reconstructing a whole new `SecVec`. It also might promote more secure usage of this struct for cases as mentioned above.

What are your thoughts? Can something like this be implemented? I'd be happy to implement this in a PR!

**Comment by myfreeweb** [comment]
Go ahead, I merge practically anything here :)
