### ISSUE TITLE
Make SecStr newtype that enforces UTF-8

### ISSUE THREAD

**Issue by dvic** [myfreeweb/secstr#7]
What do you think of making `SecStr` a new-type wrapper that enforces UTF-8, since the name is hinting that it contains a valid `String` and in Rust a valid string is always `UTF-8`. It would be something like:

```rust
pub struct SecStr(secstr::SecVec<u8>);

impl From<String> for SecStr {
    fn from(s: String) -> SecStr {
        SecStr(secstr::SecVec::from(s))
    }
}

impl SecStr {
    pub fn unsecure(&self) -> &str {
        std::str::from_utf8(self.0.unsecure()).expect("cast SecStr to utf8")
    }
}
```

I can submit a PR if you agree with the idea.

**Comment by myfreeweb** [comment]
Yeah, good idea. I'm not sure about the API breakage, maybe name it something else? Something like `SecString` or `SecUtf8` might be okay.

Also, if you make it a struct with a single private field, you could use `from_utf8_unchecked` in `unsecure`.
